import java.awt.Color;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Adan Jesus
 */
public class login extends javax.swing.JFrame {
    public Connection conectar(){
  
        Connection con = null;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3307/biblos","root","");
           
        } catch (SQLException e) {
          System.err.print(e.toString() );
          JOptionPane.showMessageDialog(this, "Ocurrio un error inesperado");
        }
       return con;
       }
     public void ingresar  (){
     Connection con1 = null;
     ResultSet rs = null;
     PreparedStatement ps = null;
     String usuario = txtUsuario.getText();
     String contra = txtContra.getText();
     
     if (usuario.equals("") || contra.equals("") ){
         JOptionPane.showMessageDialog(this,"Uno o mas campos estan vacios");
     } else {
         try{
            con1 = conectar();
            ps= con1.prepareStatement("select usuario,contraseña from registro where usuario='"+usuario
                    +"' and contraseña = '"+contra+"'");
            rs = ps.executeQuery();
            if(rs.next()){
                this.dispose();
                new IntVentas().setVisible(true);
            } else {
                     JOptionPane.showMessageDialog(this,"Credenciales incorrecta, por favor vuelve a intentarlo");
            }
         } catch (SQLException e){
             System.err.print(e.toString());
     
                      JOptionPane.showMessageDialog(this,"Ocurrio un error inesperado, favor comunicar al desarrollador");
     }
     }

     }
    public login() {
        initComponents();
       
        this.setLocationRelativeTo(this);

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PanelLibreria = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        BtnInico = new javax.swing.JButton();
        BtnRegistro = new javax.swing.JButton();
        lblContra = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtContra = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(new java.awt.Dimension(850, 440));
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel3.setText("Libreria Biblos ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 150, 30));

        jLabel4.setFont(new java.awt.Font("DialogInput", 3, 12)); // NOI18N
        jLabel4.setText("¿Aun no te has registrado?");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, 44));

        PanelLibreria.setBackground(new java.awt.Color(255, 255, 255));
        PanelLibreria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PanelLibreria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/La-biblioteca-es-inclusion-social-e-igualdad-de-oportunidades.jpg"))); // NOI18N
        jPanel2.add(PanelLibreria, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 370, 440));
        PanelLibreria.getAccessibleContext().setAccessibleName("");

        lblUsuario.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblUsuario.setText("Usuario:");
        jPanel2.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 70, -1));

        BtnInico.setBackground(new java.awt.Color(51, 102, 255));
        BtnInico.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        BtnInico.setForeground(new java.awt.Color(255, 255, 255));
        BtnInico.setText("Iniciar sesion");
        BtnInico.setBorder(null);
        BtnInico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInicoActionPerformed(evt);
            }
        });
        jPanel2.add(BtnInico, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 156, 50));

        BtnRegistro.setBackground(new java.awt.Color(51, 102, 255));
        BtnRegistro.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        BtnRegistro.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegistro.setText("Registrarse");
        BtnRegistro.setBorder(null);
        BtnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistroActionPerformed(evt);
            }
        });
        jPanel2.add(BtnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 156, 50));

        lblContra.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblContra.setText("Contraseña:");
        jPanel2.add(lblContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 86, -1));

        txtUsuario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtUsuario.setText(" ");
        txtUsuario.setBorder(null);
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuarioMousePressed(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 400, 20));

        txtContra.setBorder(null);
        txtContra.setName("txtContra"); // NOI18N
        txtContra.setPreferredSize(new java.awt.Dimension(64, 25));
        txtContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtContraMousePressed(evt);
            }
        });
        txtContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraActionPerformed(evt);
            }
        });
        jPanel2.add(txtContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 410, 20));

        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 177, 410, -1));

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 267, 420, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void BtnInicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInicoActionPerformed
            ingresar();
        
    }//GEN-LAST:event_BtnInicoActionPerformed

    private void BtnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistroActionPerformed
            this.dispose();
            new Registro().setVisible(true);
    }//GEN-LAST:event_BtnRegistroActionPerformed

    private void txtContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraActionPerformed

    private void txtUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMousePressed
        // TODO add your handling code here:
     
  
    }//GEN-LAST:event_txtUsuarioMousePressed

    private void txtContraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContraMousePressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_txtContraMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new login().setVisible(true);
           

        });
        
    }
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnInico;
    private javax.swing.JButton BtnRegistro;
    private javax.swing.JLabel PanelLibreria;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblContra;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txtContra;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
